version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: exchanging_app_dev
    ports:
      - "8000:8000"
      - "5678:5678"  # デバッグ用ポート
    volumes:
      - ..:/app:cached
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    command: sleep infinity  # Dev Container用に無限待機
    stdin_open: true
    tty: true
    networks:
      - dev-network

  # データベース（開発用）
  db:
    image: postgres:15-alpine
    container_name: exchanging_db_dev
    environment:
      POSTGRES_DB: exchanging_app_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev-network

  # Redis（開発用）
  redis:
    image: redis:7-alpine
    container_name: exchanging_redis_dev
    ports:
      - "6379:6379"
    networks:
      - dev-network

volumes:
  postgres_dev_data:

networks:
  dev-network:
    driver: bridge
