version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: exchange_analytics_postgresql
    environment:
      POSTGRES_DB: exchange_analytics
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./postgresql_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./postgresql_init.sql:/docker-entrypoint-initdb.d/02-init.sql
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=8
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exchange_user -d exchange_analytics"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: exchange_analytics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exchange-analytics.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql
    restart: unless-stopped

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: exchange_analytics_network
