investpy:
  default_timezone: "GMT +9:00"
  time_filter: "time_only"
  default_countries:
    - "japan"
    - "united states"
    - "euro zone"
    - "united kingdom"
    - "australia"
    - "canada"
  default_importances:
    - "high"
    - "medium"
  retry_attempts: 3
  retry_delay: 5

scheduling:
  weekly:
    day: "sunday"
    time: "09:00"
    timezone: "Asia/Tokyo"
  daily:
    time: "07:00"
    timezone: "Asia/Tokyo"
  realtime:
    check_interval: 30 # minutes
    pre_announcement: 60 # minutes before event
    post_announcement: 15 # minutes after event

notification:
  discord:
    webhook_url: "${DISCORD_WEBHOOK_URL}"
    username: "Economic Calendar Bot"
    avatar_url: ""
    cooldown_period: 3600 # seconds
  rules:
    importance_threshold: "medium"
    countries_filter:
      - "japan"
      - "united states"
      - "euro zone"
      - "united kingdom"
      - "australia"
      - "canada"
    categories_filter:
      - "inflation"
      - "employment"
      - "interest_rate"
      - "gdp"
    forecast_change_threshold: 0.1 # 10% change

ai_analysis:
  openai:
    model: "gpt-4"
    max_tokens: 2000
    temperature: 0.3
    api_key: "${OPENAI_API_KEY}"
  report_generation:
    pre_event_hours: 24  # イベント前24時間
    post_event_hours: 2   # イベント後2時間
    importance_threshold: "high"  # 高重要度のみ
    target_events:
      - "Consumer Price Index (CPI)"
      - "Gross Domestic Product (GDP)"
      - "Employment Report"
      - "Interest Rate Decision"
      - "Bank of Japan Policy Rate"
      - "Federal Reserve Interest Rate Decision"
      - "ECB Interest Rate Decision"
      - "Bank of England Interest Rate Decision"
      - "Non-Farm Payrolls"
      - "Eurozone CPI"
      - "UK CPI"
  usd_jpy_analysis:
    timeframe: "1-4 hours"  # 予測時間枠
    confidence_threshold: 0.7  # 信頼度閾値
    include_technical_analysis: true
    include_fundamental_analysis: true
