# Logging Configuration for Exchange Analytics
# 設計書参照: フォルダ構成実装ガイド_20250809.md

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    format: "%(asctime)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

  simple:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_access:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/access.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  # For production monitoring
  syslog:
    class: logging.handlers.SysLogHandler
    level: WARNING
    formatter: json
    address: localhost:514

loggers:
  # Root logger
  root:
    level: INFO
    handlers: [console, file_info, file_error]

  # Application loggers
  exchange_analytics:
    level: DEBUG
    handlers: [console, file_info, file_error]
    propagate: false

  # Domain layer loggers
  exchange_analytics.domain:
    level: INFO
    handlers: [file_info]
    propagate: true

  # Application layer loggers
  exchange_analytics.application:
    level: INFO
    handlers: [file_info]
    propagate: true

  # Infrastructure layer loggers
  exchange_analytics.infrastructure:
    level: INFO
    handlers: [file_info]
    propagate: true

  exchange_analytics.infrastructure.database:
    level: WARNING
    handlers: [file_info]
    propagate: true

  exchange_analytics.infrastructure.external_apis:
    level: INFO
    handlers: [file_info]
    propagate: true

  # Presentation layer loggers
  exchange_analytics.presentation:
    level: INFO
    handlers: [file_info, file_access]
    propagate: true

  # Plugin system loggers
  exchange_analytics.plugins:
    level: INFO
    handlers: [file_info]
    propagate: true

  # External library loggers
  sqlalchemy:
    level: WARNING
    handlers: [file_info]
    propagate: false

  sqlalchemy.engine:
    level: WARNING
    handlers: [file_info]
    propagate: false

  requests:
    level: WARNING
    handlers: [file_info]
    propagate: false

  urllib3:
    level: WARNING
    handlers: [file_info]
    propagate: false

  aiohttp:
    level: INFO
    handlers: [file_info]
    propagate: false

  # Development-specific loggers
  werkzeug:
    level: INFO
    handlers: [console]
    propagate: false

# Environment-specific configurations
development:
  loggers:
    exchange_analytics:
      level: DEBUG
    sqlalchemy.engine:
      level: INFO  # Show SQL queries in development

production:
  loggers:
    root:
      level: WARNING
      handlers: [file_info, file_error, syslog]
    exchange_analytics:
      level: INFO
      handlers: [file_info, file_error, syslog]

testing:
  loggers:
    root:
      level: CRITICAL
      handlers: [console]
    exchange_analytics:
      level: WARNING
      handlers: [console]
