# Logging Configuration for Exchange Analytics
# 設計書参照: フォルダ構成実装ガイド_20250809.md

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file_app:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/app.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /app/data/logs/error.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8
  
  file_scheduler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/scheduler/scheduler.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8
  
  file_notifications:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/notifications/notifications.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8
  
  file_ai_analysis:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/ai_analysis/ai_analysis.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8
  
  file_database:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/database/database.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8
  
  file_monitoring:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/monitoring/monitoring.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8

loggers:
  # ルートロガー
  "":
    level: INFO
    handlers: [console, file_app, file_error]
    propagate: false
  
  # アプリケーションロガー
  src:
    level: INFO
    handlers: [console, file_app]
    propagate: false
  
  # スケジューラーロガー
  src.application.interfaces.schedulers:
    level: INFO
    handlers: [file_scheduler]
    propagate: false
  
  # 通知ロガー
  src.application.use_cases.notification:
    level: INFO
    handlers: [file_notifications]
    propagate: false
  
  # AI分析ロガー
  src.application.use_cases.ai_report:
    level: INFO
    handlers: [file_ai_analysis]
    propagate: false
  
  # データベースロガー
  src.infrastructure.database:
    level: INFO
    handlers: [file_database]
    propagate: false
  
  # 監視ロガー
  scripts.monitor_service:
    level: INFO
    handlers: [file_monitoring]
    propagate: false
  
  # 外部APIロガー
  src.infrastructure.external:
    level: INFO
    handlers: [file_app]
    propagate: false
  
  # エラーロガー
  error:
    level: ERROR
    handlers: [file_error]
    propagate: false

root:
  level: INFO
  handlers: [console, file_app, file_error]
