notification_patterns:
  new_high_importance_event:
    enabled: true
    conditions:
      importance: "high"
      countries: ["japan", "united states", "euro zone"]
    message_template: "🚨 重要経済指標: {country} - {event_name} ({date} {time})"

  forecast_change:
    enabled: true
    conditions:
      change_threshold: 0.1
      importance: ["high", "medium"]
    message_template: "📊 予測値変更: {country} - {event_name} 予測: {old_forecast} → {new_forecast}"

  actual_announcement:
    enabled: true
    conditions:
      importance: ["high", "medium"]
    message_template: "📈 発表: {country} - {event_name} 実際: {actual} (予測: {forecast})"

  surprise_alert:
    enabled: true
    conditions:
      surprise_threshold: 0.2
      importance: "high"
    message_template: "⚠️ サプライズ: {country} - {event_name} 予測差: {surprise_percentage}%"

  ai_report_alert:
    enabled: true
    conditions:
      importance: "high"
      event_types: ["CPI", "GDP", "Employment", "Interest Rate"]
    message_template: "🤖 AI分析: {country} - {event_name} ドル円予測レポート生成完了"
    include_report_summary: true

message_formatting:
  embed_color:
    high_importance: 0xFF0000
    medium_importance: 0xFFA500
    low_importance: 0x00FF00
  timezone_display: "Asia/Tokyo"
  date_format: "%Y-%m-%d %H:%M"
